# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

# Inherit AOSP product
$(call inherit-product, device/google/sunfish/aosp_sunfish.mk)
# Inherit Pixel product
$(call inherit-product, vendor/pixel/products/pixel_sunfish.mk)

# Match stock product info
PRODUCT_NAME := sunfish
PRODUCT_MODEL := Pixel 4a
PRODUCT_BRAND := google
PRODUCT_MANUFACTURER := Google
